apiVersion: v1
kind: Service
metadata:
  name: nuxt-basic-starter-service
  namespace: nuxt-basic-starter
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: nuxt-basic-starter
